# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build master with Maven


on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: ./mvnw -B verify
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
    - name: Upload to Codecov (ITest)
      uses: codecov/codecov-action@v2.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./target/site/jacoco-it/jacoco.xml
        flags: integrationtests
